services:
  app:
    build: .
    image: app_route
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: on-failure

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: web_route
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webRoutes
    ports:
      - "5433:5432"
    volumes:
      - ./internal/repositories/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s